---
title: "p8105_hw5_rac2224"
author: "Rachel Crowley"
date: "11/11/2019"
output: github_document
---

## Problem 1

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

mean_nonmiss = function(x) {
  x[is.na(x)] <- round(mean(x, na.rm = TRUE), 1)
  x
  x[is.character(x)] <- replace_na(x, "virginica")
}

output = map_df(.x = iris_with_missing, ~ mean_nonmiss(.x))
```

## Problem 2

Reading in the data for each subject and creating two new columns for ID and Arm (control vs. experimental)
```{r}
case_control = 
  list.files(path = "./data", full.names = TRUE)

read_obs = function(path) {
     test = read.csv(path)
     arm = str_split( path, pattern = "_", simplify = TRUE)
     type <- paste(c("con","exp"), collapse="|")
     test$control_arm = str_extract_all(arm[, ncol(arm) - 1], pattern = type )
     test$subject_id = str_extract(arm[, ncol(arm)], pattern = "\\d{1,2}")
     test
}

all_data = map_df(.x = case_control, ~read_obs(.x))
```

Further tidying the dataset

```{r}
all_data = all_data %>%
  janitor::clean_names() %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week", 
    names_prefix = "week_",
    values_to = "observation") 
```
